# Face ID project

### Haar Cascades

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

def showImg(img, title = ''):
    plt.figure(figsize = (10,10));
    plt.title(title)
    plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

def showGrayScaleImg(img, title = ''):
    plt.figure(figsize = (10,10));
    plt.title(title)
    plt.imshow(img, cmap='gray')

all_contours = -1
green = (0,255,0)
thickness = 2

new_img = cv2.UMat(cv2.IMREAD_COLOR)


#####################################3

image_template = []

image_template.append(cv2.imread('img/eva.jpg')) 
image_template.append(cv2.imread('img/edgar.jpg'))
#for i in range(len(image_template)):
 #   showImg(image_template[i])
    
####################################3

def ORB_detector(new_image, image_template):
    # Function that compares input image to template
    # It then returns the number of ORB matches between them
    
    image1 = cv2.cvtColor(new_image, cv2.COLOR_BGR2GRAY)
    
    #showImg(image1)
    
    # Create ORB detector with 1000 keypoints with a scaling pyramid factor of 1.2
    orb = cv2.ORB_create(1000, 1.2)
    
    # Detect keypoints of original image
    (kp1, des1) = orb.detectAndCompute(image1, None)

    # Detect keypoints of rotated image
    (kp2, des2) = orb.detectAndCompute(image_template, None)

    # Create matcher     
    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)

    # Do matching
    matches = bf.match(des1,des2)

    # Sort the matches based on distance.  Least distance
    # is better
    matches = sorted(matches, key=lambda val: val.distance)
    
    if len(matches) > 210:
        matches_img = cv2.drawMatches(image1,kp1,image_template,kp2,matches[:20],None)
        cv2.imwrite('orbMatches.jpg',matches_img)

    return matches

#################################################






In [ ]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)

while True:

    # Get webcam images
    ret, frame = cap.read()

    height, width = frame.shape[:2]

    top_left_x = width // 3
    top_left_y = (height // 2) + (height // 4)
    bottom_right_x = (width // 3) * 2
    bottom_right_y = (height // 2) - (height // 4)

    faces = face_classifier.detectMultiScale(frame, 1.3, 5)
    print(faces)
    
    people_values =[]
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (127,0,255), 2)
    
        magin = 30
        top_left_x = x-magin
        top_left_y = y-magin
        bottom_right_x = x+w+magin
        bottom_right_y = y+h+magin
    

        cropped = frame[top_left_y:bottom_right_y, top_left_x:bottom_right_x]
  
        # Repasa todas las caras 
        for i in range(len(image_template)):
            matches = ORB_detector(cropped, image_template[i])
            
            people_values.append(matches)

        threshold = 150

        # If matches exceed our threshold then object has been detected
        for i in range(len(image_template)):
            
            if len(people_values[i]) > threshold:
                #frame = frame.copy()
                if i == 0:
                    text = "Eva "+str(len(people_values[i]))
                    #cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
                    cv2.putText(frame,text,(int(top_left_x+w/2),top_left_y-20), cv2.FONT_HERSHEY_COMPLEX, 1 ,(127,0,255), 2) 

                elif i == 1:
                    text = "Edgar "+str(len(people_values[i]))
                    #cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
                    cv2.putText(frame,text,(int(top_left_x+w/2),top_left_y+10), cv2.FONT_HERSHEY_COMPLEX, 1 ,(127,0,255), 2) 

                
                
        # Flip frame orientation horizontally
  #  frame = cv2.flip(frame,1)
            
    cv2.imshow('Object Detector using ORB', frame)
    
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[479 255 354 354]]
[[468 240 382 382]]
[[473 243 370 370]]
[[469 235 382 382]]
[[474 239 374 374]]
[[468 242 367 367]]
[[455 239 374 374]]
[[461 240 364 364]]
[[477 237 370 370]]
[[466 238 361 361]]
[[457 235 369 369]]
[[451 231 378 378]]
[[456 235 370 370]]
[[460 236 368 368]]
[[460 235 371 371]]
[[453 231 378 378]]
[[460 235 370 370]]
[[454 227 385 385]]
[[443 219 375 375]]
[[442 209 340 340]]
[[461 213 307 307]]
[[398 214 274 274]]
[[350 211 283 283]]
[[375 217 293 293]]
[[415 208 293 293]]
[[403 189 291 291]]
[[402 172 312 312]]
[[425 157 308 308]]
[[426 178 303 303]]
[[425 176 303 303]]
[[413 177 317 317]]
[[413 185 312 312]]
[[408 189 321 321]]
[[420 193 305 305]]
[[418 191 308 308]]
[[418 191 309 309]]
[[424 196 298 298]]
[[420 195 302 302]]
[[423 194 299 299]]
[[422 195 300 300]]
[[418 195 303 303]]
[[416 192 308 308]]
[[412 193 310 310]]
[[414 194 305 305]]
[[414 192 303 303]]
[[417 196 302 302]]
[[414 196 306 306]]
[[415 192 309 309]]
[[414 189 314 314]]
[[423 194 299 299]]
